[project]
name = "usaible"
version = "0.1.0"
description = "Minimcal FastMCP server and client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "langgraph>=0.4.8",
]
