[project]
name = "minimcp"
version = "0.1.0"
description = "Example code for MCP-enabled LLM agents"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "langgraph>=0.4.8",
]
